# Site Başlık ve Açıklaması
title: "HTB Çözümlerim"
description: "Hack The Box makinelerine ait çözüm notları."

# Tema Ayarları
theme: jekyll-theme-minimal

# Permalink Yapısı
permalink: /:title

# Markdown Formatı
markdown: kramdown
